// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID    `json:"id"`
	Email         string       `json:"email"`
	Username      string       `json:"username"`
	CognitoUserID string       `json:"cognito_user_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}
