// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Deployment struct {
	ID         uuid.UUID      `json:"id"`
	ProjectID  uuid.UUID      `json:"project_id"`
	UserID     uuid.UUID      `json:"user_id"`
	CommitHash string         `json:"commit_hash"`
	Branch     string         `json:"branch"`
	Status     string         `json:"status"`
	Logs       sql.NullString `json:"logs"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Project struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	RepositoryUrl  string         `json:"repository_url"`
	BuildCommand   sql.NullString `json:"build_command"`
	RunCommand     string         `json:"run_command"`
	Language       string         `json:"language"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	InstallCommand string         `json:"install_command"`
	// Custom subdomain prefix for the project (e.g., "my-app" becomes "my-app.snapdeploy.app")
	CustomDomain string `json:"custom_domain"`
}

// Stores encrypted environment variables for projects
type ProjectEnvironmentVariable struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
	// Encrypted environment variable value (AES-256-GCM)
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Repository struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	GithubID        int64          `json:"github_id"`
	Name            string         `json:"name"`
	FullName        string         `json:"full_name"`
	Description     sql.NullString `json:"description"`
	Url             string         `json:"url"`
	HtmlUrl         sql.NullString `json:"html_url"`
	Private         sql.NullBool   `json:"private"`
	Fork            sql.NullBool   `json:"fork"`
	StargazersCount sql.NullInt32  `json:"stargazers_count"`
	WatchersCount   sql.NullInt32  `json:"watchers_count"`
	ForksCount      sql.NullInt32  `json:"forks_count"`
	DefaultBranch   sql.NullString `json:"default_branch"`
	Language        sql.NullString `json:"language"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID    `json:"id"`
	Email       string       `json:"email"`
	Username    string       `json:"username"`
	ClerkUserID string       `json:"clerk_user_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}
