// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_env_vars.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CountProjectEnvVars = `-- name: CountProjectEnvVars :one
SELECT COUNT(*) FROM project_environment_variables
WHERE project_id = $1
`

func (q *Queries) CountProjectEnvVars(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountProjectEnvVars, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateProjectEnvVar = `-- name: CreateProjectEnvVar :one
INSERT INTO project_environment_variables (
    project_id,
    key,
    value
) VALUES (
    $1, $2, $3
)
RETURNING id, project_id, key, value, created_at, updated_at
`

type CreateProjectEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
}

func (q *Queries) CreateProjectEnvVar(ctx context.Context, arg *CreateProjectEnvVarParams) (*ProjectEnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, CreateProjectEnvVar, arg.ProjectID, arg.Key, arg.Value)
	var i ProjectEnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteAllProjectEnvVars = `-- name: DeleteAllProjectEnvVars :exec
DELETE FROM project_environment_variables
WHERE project_id = $1
`

func (q *Queries) DeleteAllProjectEnvVars(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteAllProjectEnvVars, projectID)
	return err
}

const DeleteProjectEnvVar = `-- name: DeleteProjectEnvVar :exec
DELETE FROM project_environment_variables
WHERE project_id = $1 AND key = $2
`

type DeleteProjectEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) DeleteProjectEnvVar(ctx context.Context, arg *DeleteProjectEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, DeleteProjectEnvVar, arg.ProjectID, arg.Key)
	return err
}

const GetProjectEnvVar = `-- name: GetProjectEnvVar :one
SELECT id, project_id, key, value, created_at, updated_at FROM project_environment_variables
WHERE project_id = $1 AND key = $2
`

type GetProjectEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetProjectEnvVar(ctx context.Context, arg *GetProjectEnvVarParams) (*ProjectEnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, GetProjectEnvVar, arg.ProjectID, arg.Key)
	var i ProjectEnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetProjectEnvVars = `-- name: GetProjectEnvVars :many
SELECT id, project_id, key, value, created_at, updated_at FROM project_environment_variables
WHERE project_id = $1
ORDER BY key ASC
`

func (q *Queries) GetProjectEnvVars(ctx context.Context, projectID uuid.UUID) ([]*ProjectEnvironmentVariable, error) {
	rows, err := q.db.QueryContext(ctx, GetProjectEnvVars, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProjectEnvironmentVariable{}
	for rows.Next() {
		var i ProjectEnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProjectEnvVar = `-- name: UpdateProjectEnvVar :one
UPDATE project_environment_variables
SET 
    value = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND key = $2
RETURNING id, project_id, key, value, created_at, updated_at
`

type UpdateProjectEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
}

func (q *Queries) UpdateProjectEnvVar(ctx context.Context, arg *UpdateProjectEnvVarParams) (*ProjectEnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, UpdateProjectEnvVar, arg.ProjectID, arg.Key, arg.Value)
	var i ProjectEnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
