// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CreateUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (id, user_id, default_branch)
VALUES ($1, $2, $3)
RETURNING id, user_id, default_branch, created_at, updated_at
`

type CreateUserSettingsParams struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	DefaultBranch sql.NullString `json:"default_branch"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg *CreateUserSettingsParams) (*UserSetting, error) {
	row := q.db.QueryRowContext(ctx, CreateUserSettings, arg.ID, arg.UserID, arg.DefaultBranch)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteUserSettings = `-- name: DeleteUserSettings :exec
DELETE FROM user_settings
WHERE user_id = $1
`

func (q *Queries) DeleteUserSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteUserSettings, userID)
	return err
}

const GetUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
SELECT id, user_id, default_branch, created_at, updated_at FROM user_settings
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (*UserSetting, error) {
	row := q.db.QueryRowContext(ctx, GetUserSettingsByUserID, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET default_branch = $1, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
RETURNING id, user_id, default_branch, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	DefaultBranch sql.NullString `json:"default_branch"`
	UserID        uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg *UpdateUserSettingsParams) (*UserSetting, error) {
	row := q.db.QueryRowContext(ctx, UpdateUserSettings, arg.DefaultBranch, arg.UserID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (id, user_id, default_branch)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) 
DO UPDATE SET 
    default_branch = EXCLUDED.default_branch,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, default_branch, created_at, updated_at
`

type UpsertUserSettingsParams struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	DefaultBranch sql.NullString `json:"default_branch"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg *UpsertUserSettingsParams) (*UserSetting, error) {
	row := q.db.QueryRowContext(ctx, UpsertUserSettings, arg.ID, arg.UserID, arg.DefaultBranch)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
